### PR TITLE
DOC: further install instructions and KubeCluster hyperlink

### LINKED ISSUE #240: add conda forge install instructions
add conda forge install instructions here https://kubernetes.dask.org/en/latest/#install (https://github.com/dask/dask-kubernetes/blob/master/doc/source/index.rst#install).

Could copy from dask-jobqueue https://jobqueue.dask.org/en/latest/install.html#installing

### LINKED ISSUE #241: doc hyperlinlink to KubeCluster
In https://github.com/dask/dask-kubernetes/blob/master/doc/source/index.rst#best-practices under 1. It says 'See KubeCluster docstring below for guidance on how to check and modify this.'. I believe there is a way to hyperlink it to https://kubernetes.dask.org/en/latest/api.html#dask_kubernetes.KubeCluster

### PR DESCRIPTION
**Pull request by raybellwaves**
Closes #240 #241

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Thanks @raybellwaves.

The CI failures seem unrelated.

**Comment by raybellwaves** [comment]
ping

**Comment by jsignell** [comment]
Hi @raybellwaves, sorry this dropped off the radar - Jacob has been out. It looks good to me.

**Comment by TomAugspurger** [comment]
Thanks!

**Pull request merged**
