### PR TITLE
Clarify how to run tests locally

### LINKED ISSUE #288: Running the tests from master branch fail - "Couldn't gather keys"
**What happened**:

make test doesn't work. I keep having the following log which will continuously go on and on for the test "test_cluster_create":
```
dask_kubernetes/tests/test_async.py::test_cluster_create distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:   tcp://192.168.2.4:46337
distributed.scheduler - INFO -   dashboard at:                     :8787
distributed.scheduler - INFO - Receive client connection: Client-291dabe6-4152-11eb-869b-9cb6d0f7a683
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Register worker <Worker 'tcp://10.244.0.10:36501', name: 0, memory: 0, processing: 1>
distributed.scheduler - INFO - Starting worker compute stream, tcp://10.244.0.10:36501
distributed.core - INFO - Starting established connection
distributed.scheduler - ERROR - Couldn't gather keys {'lambda-abb84b7bea08dbbd080ed10c969c7abc': ['tcp://10.244.0.10:36501']} state: ['memory'] workers: ['tcp://10.244.0.10:36501']
NoneType: None
distributed.scheduler - INFO - Remove worker <Worker 'tcp://10.244.0.10:36501', name: 0, memory: 1, processing: 0>
distributed.core - INFO - Removing comms to tcp://10.244.0.10:36501
distributed.scheduler - INFO - Lost all workers
distributed.scheduler - ERROR - Workers don't have promised key: ['tcp://10.244.0.10:36501'], lambda-abb84b7bea08dbbd080ed10c969c7abc
NoneType: None
distributed.client - WARNING - Couldn't gather 1 keys, rescheduling {'lambda-abb84b7bea08dbbd080ed10c969c7abc': ('tcp://10.244.0.10:36501',)}
distributed.scheduler - INFO - Register worker <Worker 'tcp://10.244.0.10:36501', name: 0, memory: 0, processing: 1>
distributed.scheduler - INFO - Starting worker compute stream, tcp://10.244.0.10:36501
distributed.core - INFO - Starting established connection
^Cdistributed.scheduler - INFO - Scheduler closing...
distributed.scheduler - INFO - Scheduler closing all comms
distributed.scheduler - INFO - Remove worker <Worker 'tcp://10.244.0.10:36501', name: 0, memory: 1, processing: 0>
distributed.core - INFO - Removing comms to tcp://10.244.0.10:36501
distributed.scheduler - INFO - Lost all workers
```

**Anything else we need to know?**:

I tried to keep the environment the same as much as possible, but I'm not sure these minor differences are causing the issue. Worker log:
```
+ '[' '' ']'
+ '[' -e /opt/app/environment.yml ']'
+ echo 'no environment.yml'
+ '[' '' ']'
+ '[' '' ']'
+ exec dask-worker tcp://192.168.2.4:46337 --nthreads 1 --death-timeout 60 --name 0
no environment.yml
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.244.0.10:40809'
distributed.worker - INFO -       Start worker at:    tcp://10.244.0.10:36501
distributed.worker - INFO -          Listening to:    tcp://10.244.0.10:36501
distributed.worker - INFO -          dashboard at:          10.244.0.10:46435
distributed.worker - INFO - Waiting to connect to:    tcp://192.168.2.4:46337
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    2.08 GB
distributed.worker - INFO -       Local Directory: /usr/local/src/dask-worker-space/dask-worker-space/worker-07732v9v
distributed.worker - INFO - -------------------------------------------------
distributed.worker - WARNING - Mismatched versions found

+---------+------------------------+------------------------+------------------------------------------------------+
| Package | This Worker            | scheduler              | workers                                              |
+---------+------------------------+------------------------+------------------------------------------------------+
| dask    | 2020.12.0+13.g76ea3379 | 2020.12.0+15.g30e64df0 | {'2020.12.0+13.g76ea3379', '2020.12.0+15.g30e64df0'} |
| python  | 3.8.0.final.0          | 3.8.5.final.0          | {'3.8.5.final.0', '3.8.0.final.0'}                   |
+---------+------------------------+------------------------+------------------------------------------------------+
distributed.worker - INFO -         Registered to:    tcp://192.168.2.4:46337
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.worker - WARNING - Mismatched versions found

+---------+------------------------+------------------------+------------------------------------------------------+
| Package | This Worker            | scheduler              | workers                                              |
+---------+------------------------+------------------------+------------------------------------------------------+
| dask    | 2020.12.0+13.g76ea3379 | 2020.12.0+15.g30e64df0 | {'2020.12.0+13.g76ea3379', '2020.12.0+15.g30e64df0'} |
| python  | 3.8.0.final.0          | 3.8.5.final.0          | {'3.8.5.final.0', '3.8.0.final.0'}                   |
+---------+------------------------+------------------------+------------------------------------------------------+
distributed.worker - INFO -         Registered to:    tcp://192.168.2.4:46337
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO - Stopping worker at tcp://10.244.0.10:36501
distributed.nanny - INFO - Worker closed
distributed.dask_worker - INFO - Exiting on signal 15
distributed.nanny - INFO - Closing Nanny at 'tcp://10.244.0.10:40809'
distributed.nanny - INFO - Worker process 18 was killed by signal 15
distributed.dask_worker - INFO - End worker
```

**Environment**:

- Dask version: 2012.12.0
- Python version: 3.8
- Operating System: Arch linux
- Install method (conda, pip, source): clone of master
- kubernetes: Kind

### PR DESCRIPTION
**Pull request by pvanderlinden**
Closes #288 

I believe these changes to the docs make it easier for people to understand how to get this up and running.

Maybe the docs should also refer to this setup from quickstart?

### CODE REVIEW

**Comment by pvanderlinden** [comment]
I'm not sure why testing fails, I have not changed any code.

**Comment by jacobtomlinson** [comment]
Many thanks!

**Comment by jacobtomlinson** [comment]
> Maybe the docs should also refer to this setup from quickstart?

Quickstart is for users, not developers. So I'm not sure that makes sense.

> I'm not sure why testing fails, I have not changed any code.

Test failures are unrelated here.

**Comment by pvanderlinden** [comment]
> > Maybe the docs should also refer to this setup from quickstart?
> 
> Quickstart is for users, not developers. So I'm not sure that makes sense.
> 
> > I'm not sure why testing fails, I have not changed any code.
> 
> Test failures are unrelated here.

I do understand the testing setup is for people wanting to contribute to dask-kubernetes. The quickstart won't get you far as a user though, unless I read over some instructions. I didn't see any mention of needing to run the code example in a container on the kubernetes cluster itself (with the RBAC applied and all), I assumed that I could run this code from my local computer while connectin it to a minikube cluster. @jacobtomlinson

**Comment by jacobtomlinson** [comment]
Dask Kubernetes grew from the [Pangeo community](https://pangeo.io/) which was focussed on deploying Jupyter Hub with geoscience specific environments. This library was intended to be used from within a Jupyter Lab session which had been spawned on the kubernetes cluster.

Therefore there are a bunch of assumptions that this is being used from within the cluster, with access to pod networking, etc. Some work has been done to run the scheduler within the cluster and expose it as a service, but this is not yet well documented.

Connecting from your local computer to a minikube instance on that same machine is not a real world use case, just a developer one. Hence the setup being included in the developer documentation.

**Pull request merged**
