### PR TITLE
Use yaml.safe_load

### PR DESCRIPTION
**Pull request by mrocklin**
Recent versions of pyyaml now raise warnings on yaml.load

### CODE REVIEW

**Comment by jcrist** [comment]
LGTM, merging.

**Comment by mrocklin** [comment]
Thanks for noticing that this was lingering @jcrist

**Comment by jcrist** [comment]
This was against the `dask:dev` branch, is there a reason it wasn't against master?

**Comment by mrocklin** [comment]
There is a lot of work in dev to make dask-kubernetes async-friendly.  I would like to see that branch become dominant, but there is enough uncertainty that I didn't want to force it.

At this point I think that it's *probably* a good idea to merge dev into master?

**Comment by jcrist** [comment]
Care to make a PR of dev against master?

**Comment by mrocklin** [comment]
https://github.com/dask/dask-kubernetes/pull/138/

**Pull request merged**
