### PR TITLE
Bump kubernetes client library to 6.0.0

### PR DESCRIPTION
**Pull request by mrocklin**

### CODE REVIEW

**Comment by rabernat** [comment]
bummer!

**Comment by rabernat** [comment]
Do you imagine merging this soon? If so, we can install from the latest dask-kubernetes master.

**Comment by mrocklin** [comment]
I would probably merge the config PR first, and then this on top (that
seems to make circle-ci happy).  This isn't super high on my priority list
at the moment, but I can bump it up if you'd prefer.

**Comment by mrocklin** [comment]
Although, after I merge the config PR it will be unusable except with
master versions of dask/dask and dask/distributed, which may not be what
you want

**Comment by rabernat** [comment]
No rush. I'll just pin the older version of kubernetes.

**Comment by rabernat** [comment]
Merging the config PR will presumably require changes to other aspects of our pangeo config, no?

**Comment by mrocklin** [comment]
Several, yes.

**Pull request closed without merging**
