### PR TITLE
Fix issue of duplicated environment variables

### PR DESCRIPTION
**Pull request by jonded94**
- Fixes https://github.com/dask/dask-kubernetes/issues/841
- Small code quality cleanup

### CODE REVIEW

**Review by jacobtomlinson — COMMENTED** [review]
Could I ask you to add some tests to verify the expected behaviour?

**Review by jacobtomlinson — APPROVED** [review]
Looks great thanks!

**Comment by jonded94** [comment]
Sorry to ask here - what is your schedule for release cycles? :) It's not very clear to me when I had a look at old releases.

**Comment by jacobtomlinson** [comment]
Releases are ad-hoc. I'll make one now 😄.

**Pull request merged**
