### PR TITLE
DOC: Add documentation for contributing to dask kubernetes

### PR DESCRIPTION
**Pull request by Matt711**
It would be helpful to have a contributing page in the documentation for those who want set up their development environments correctly and contribute to Dask Kubernetes. I'll start with information on the Dask Operator (Installing the Custom Resource Definitions, running the controller, etc.)

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
There is an existing `testing` page which has some of this information. Perhaps we want to replace that with something more useful?

**Comment by Matt711** [comment]
> There is an existing `testing` page which has some of this information. Perhaps we want to replace that with something more useful?

Yes, I was thinking of deleting it and incorporating it into this new page. I would like "both" methods of testing (pytest and running the controller directly) to be on one page. I think it makes more sense for both of them to be on the Developer page.

**Comment by jacobtomlinson** [comment]
Sounds great!

**Comment by jacobtomlinson** [comment]
Enough time has passed that I'm tempted to close this out. We can always use this for further docs improvement inspiration in the future.

**Pull request closed without merging**
