### PR TITLE
Update kr8s to >=0.8.19

### PR DESCRIPTION
**Pull request by droctothorpe**

### CODE REVIEW

**Review by jacobtomlinson — APPROVED** [review]
Awesome thanks for raising this. I'm happy to see the pin relaxing as `kr8s` gets more stable.

**Comment by droctothorpe** [comment]
@jacobtomlinson would it be possible to cut a release that incorporates this?

**Comment by jacobtomlinson** [comment]
I released 2023.10.0 this morning :)

**Comment by droctothorpe** [comment]
Thank you, sir!

**Pull request merged**
