### PR TITLE
Test against Dask 2.2

### PR DESCRIPTION
**Pull request by TomAugspurger**

### CODE REVIEW

**Comment by TomAugspurger** [comment]
FYI @mrocklin a few issues.

```
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7fb5027f99b0>>, <Task finished coro=<Adaptive._adapt() done, defined at /home/circleci/miniconda/envs/dask-kubernetes-test/lib/python3.7/site-packages/distributed/deploy/adaptive.py:227> exception=AttributeError("'KubeCluster' object has no attribute 'scheduler_comm'")>)
Traceback (most recent call last):
  File "/home/circleci/miniconda/envs/dask-kubernetes-test/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/circleci/miniconda/envs/dask-kubernetes-test/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/home/circleci/miniconda/envs/dask-kubernetes-test/lib/python3.7/site-packages/distributed/deploy/adaptive.py", line 233, in _adapt
    recommendations = await self.recommendations()
  File "/home/circleci/miniconda/envs/dask-kubernetes-test/lib/python3.7/site-packages/distributed/deploy/adaptive.py", line 179, in recommendations
    n = await self.scheduler.adaptive_target(target_duration=self.target_duration)
  File "/home/circleci/miniconda/envs/dask-kubernetes-test/lib/python3.7/site-packages/distributed/deploy/adaptive.py", line 117, in scheduler
    return self.cluster.scheduler_comm
AttributeError: 'KubeCluster' object has no attribute 'scheduler_comm'
```

Will finish this up tomorrow, and hopefully get a dask-kubernetes release out as well.

**Comment by mrocklin** [comment]
Tests pass

**Comment by TomAugspurger** [comment]
Your last build may have used the cached environment. When I rebuild without a cache,

Screen Shot 2019-07-31 at 7 43 03 AM


It passes, but I see some concerning tracebacks in the output. I don't recall seeing them in your build (but I may be wrong).

```

PASSEDtornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7f8f54f1eb00>>, <Task finished coro=<Adaptive._adapt() done, defined at /home/circleci/miniconda/envs/dask-kubernetes-test/lib/python3.7/site-packages/distributed/deploy/adaptive.py:227> exception=CommClosedError("in <closed TCP>: Stream is closed: while trying to call remote method 'adaptive_target'")>)
Traceback (most recent call last):
  File "/home/circleci/miniconda/envs/dask-kubernetes-test/lib/python3.7/site-packages/distributed/comm/tcp.py", line 192, in read
    n_frames = await stream.read_bytes(8)
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/circleci/miniconda/envs/dask-kubernetes-test/lib/python3.7/site-packages/distributed/core.py", line 685, in send_recv_from_rpc
    result = await send_recv(comm=comm, op=key, **kwargs)
  File "/home/circleci/miniconda/envs/dask-kubernetes-test/lib/python3.7/site-packages/distributed/core.py", line 544, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/home/circleci/miniconda/envs/dask-kubernetes-test/lib/python3.7/site-packages/distributed/comm/tcp.py", line 212, in read
    convert_stream_closed_error(self, e)
  File "/home/circleci/miniconda/envs/dask-kubernetes-test/lib/python3.7/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError("in %s: %s" % (obj, exc))
distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/circleci/miniconda/envs/dask-kubernetes-test/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/circleci/miniconda/envs/dask-kubernetes-test/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/home/circleci/miniconda/envs/dask-kubernetes-test/lib/python3.7/site-packages/distributed/deploy/adaptive.py", line 233, in _adapt
    recommendations = await self.recommendations()
  File "/home/circleci/miniconda/envs/dask-kubernetes-test/lib/python3.7/site-packages/distributed/deploy/adaptive.py", line 179, in recommendations
    n = await self.scheduler.adaptive_target(target_duration=self.target_duration)
  File "/home/circleci/miniconda/envs/dask-kubernetes-test/lib/python3.7/site-packages/distributed/core.py", line 688, in send_recv_from_rpc
    "%s: while trying to call remote method %r" % (e, key)
distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed: while trying to call remote method 'adaptive_target'
```

**Comment by mrocklin** [comment]
That looks like a warning in distributed itself.  We should probably try/except around the adaptive calls to the scheduler so that they aren't surprised if the scheduler disappears.  That should be fixed upstream though.  I suspect that this PR is good to go and that dask-kubernetes could probably be released.

**Comment by TomAugspurger** [comment]
Thanks for confirming.

Did you want to manage a dask-kubernetes release as part of your batch of releases? If not, I can do it tomorrow.

It looks like the changes here are backwards compatible, and so can be done at any time.

**Comment by TomAugspurger** [comment]
and cc @jacobtomlinson, @jhamman if you have any comments / concerns about releasing dask-kubernetes soon.

**Comment by mrocklin** [comment]
> Did you want to manage a dask-kubernetes release as part of your batch of releases? If not, I can do it tomorrow.

I'll handle it.  I think that I'll be doing a few ...

**Comment by mrocklin** [comment]
Released

**Comment by mrocklin** [comment]
@jcrist we may need these changes in dask-yarn as well

**Pull request merged**
