### PR TITLE
Explicitly specify operator's image version

### PR DESCRIPTION
**Pull request by zoonman**
I know this is not a generic solution but it is better than a broken operator deployment.

Addresses https://github.com/dask/dask-kubernetes/issues/592

### CODE REVIEW

**Review by jacobtomlinson — COMMENTED** [review]
Really appreciate you raising this but I'm working on a longer-term solution that I intend to raise today so I'm going to close this out.

**Comment by zoonman** [comment]
You can move the `latest` tag. It will save the others from suffering ;-)

**Comment by jacobtomlinson** [comment]
That's a good idea. I can't seem to figure out how to delete the `latest` tag on ghcr.io though...

**Comment by jacobtomlinson** [comment]
Also as of #594 the only folks affected by this is anyone using the broken `:latest` referencing manifests that have now been deleted. This shouldn't be a problem going forwards.

**Comment by zoonman** [comment]
If you pull the old image and then:

```shell

docker image tag ghcr.io/dask/dask-kubernetes-operator:2022.10.1  ghcr.io/dask/dask-kubernetes-operator:latest

docker image push ghcr.io/dask/dask-kubernetes-operator:latest
```

**Comment by jacobtomlinson** [comment]
I don't want to update the tag, I want to delete it altogether. This is possible on Docker Hub and other registries but I can't seem to figure out how to do this on GitHub.

We will not need a `latest` tag going forwards because we are tightly pinning the chart/manifests to a specific version to ensure compatibility. So it makes sense to delete the old `latest` tags to avoid folks from falling into a trap.

**Pull request closed without merging**
