### PR TITLE
feat(pdb): Add support for pdb creation for remote scheduler

### PR DESCRIPTION
**Pull request by groszewn**
Adds PDB creation/deletion for the remote scheduler option within a
`KubeCluster`.

Contributes to dask/dask-kubernetes#282

Signed-off-by: Nick Groszewski <groszewn@gmail.com>

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Thansk @groszewn, could you pull in the latest fixed from master? That should get the CI running correctly.

**Comment by groszewn** [comment]
@jacobtomlinson done!

**Comment by jacobtomlinson** [comment]
Thanks @groszewn.

For future reference please don't force push to PR branches. It means we get errors like this.

image

We squash on merge anyway so it's ok to just push additional merge commits.

**Comment by groszewn** [comment]
Noted!  Will keep that in mind for future contributions.

**Comment by jacobtomlinson** [comment]
Thanks again!

**Pull request merged**
