### PR TITLE
Use kubernetes_asyncio and better support async operation

### PR DESCRIPTION
**Pull request by yuvipanda**

### CODE REVIEW

**Comment by mrocklin** [comment]
I started taking a look at this but realized that I need a bit of help getting a testing situation up with minikube .  (My previous attempts at this have failed).  Next time we're in the same room @yuvipanda I might bug you about this.  In the mean time I've moved the async tests to a new file and started using the traditional kubernetes library in the sync tests file.

**Comment by mrocklin** [comment]
```python
from dask.distributed import Client
from dask_kubernetes import KubeCluster, make_pod_spec

spec = make_pod_spec(image='daskdev/dask:latest')

cluster = KubeCluster(spec, host='0.0.0.0')
cluster.scale(2)
client = Client(cluster)
client.submit(lambda x: x + 1, 10).result()  # wait for a pod to be around to do this work
cluster.scale(0)
```

```python-traceback
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7fb67bc3fc50>>, <Task finished coro=<KubeCluster._scale_down() done, defined at /home/mrocklin/workspace/dask-kubernetes/dask_kubernetes/core.py:540> exception=RuntimeError('Timeout context manager should be used inside a task',)>)
Traceback (most recent call last):
  File "/home/mrocklin/workspace/tornado/tornado/ioloop.py", line 730, in _run_callback
    ret = callback()
  File "/home/mrocklin/workspace/tornado/tornado/ioloop.py", line 752, in _discard_future_result
    future.result()
  File "/home/mrocklin/workspace/dask-kubernetes/dask_kubernetes/core.py", line 543, in _scale_down
    pods = await self._pods()
  File "/home/mrocklin/workspace/dask-kubernetes/dask_kubernetes/core.py", line 354, in _pods
    label_selector=format_labels(self.pod_template.metadata.labels)
  File "/home/mrocklin/Software/anaconda/lib/python3.6/site-packages/kubernetes_asyncio/client/api_client.py", line 165, in __call_api
    _request_timeout=_request_timeout)
  File "/home/mrocklin/Software/anaconda/lib/python3.6/site-packages/kubernetes_asyncio/client/rest.py", line 195, in GET
    query_params=query_params))
  File "/home/mrocklin/Software/anaconda/lib/python3.6/site-packages/kubernetes_asyncio/client/rest.py", line 175, in request
    r = await self.pool_manager.request(**args)
  File "/home/mrocklin/Software/anaconda/lib/python3.6/site-packages/aiohttp/client.py", line 417, in _request
    with timer:
  File "/home/mrocklin/Software/anaconda/lib/python3.6/site-packages/aiohttp/helpers.py", line 568, in __enter__
    raise RuntimeError('Timeout context manager should be used '
RuntimeError: Timeout context manager should be used inside a task
```

cc @yuvipanda

**Comment by mrocklin** [comment]
As an update.  I've gotten essentially all of our tests working asynchronously.  This wasn't that hard (and possibly wasn't necessary), but it's encouraging to see that everything works the same.

It's clear though that synchronous (normal use by users today) operation still isn't clean.

**Comment by mrocklin** [comment]
OK, things almost work except for the failure above.  It looks like aiohttp is looking at another event loop at some point?  I'm somewhat confused here

**Comment by mrocklin** [comment]
@jacobtomlinson can you verify that things continue to not-work for you?  I expect that things will continue to not-work, but I suspect that they may not-work in a new way.

**Comment by jacobtomlinson** [comment]
I'm getting the same errors I'm afraid.

**Comment by mrocklin** [comment]
Yup, it looks like that function genuinely isn't async, which is odd.  

I wonder if this is one of those things that mypy would have caught.

If you're around to try again that would be welcome.

**Comment by mrocklin** [comment]
Oh, and you may also need distributed master

**Comment by mrocklin** [comment]
So, this is feeling closer to mergable to me.  There are still things wrong, but overall I think that this is an improvement, and I'm somewhat inclined to proceed iteratively.  There are intermittent failures though, particularly around rapidly scaling up and down, but these may (?) have been around before. 

There are also other issues with testing that I think will go away when we release a docker image with a new version of dask.distributed.

**Comment by mrocklin** [comment]
Oh, and asyncio is unfortunately chatty when the event loop closes with coroutines still running

**Comment by jacobtomlinson** [comment]
With the latest version I can create the cluster but now it doesn't seem to scale.

```python
cluster.scale(1)
```

```python-traceback
tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7fa53b9ed9d8>, <Task finished coro=<KubeCluster._scale_up() done, defined at /opt/conda/lib/python3.6/site-packages/dask_kubernetes/core.py:486> exception=RuntimeError('Timeout context manager should be used inside a task',)>)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/tornado/ioloop.py", line 759, in _run_callback
    ret = callback()
  File "/opt/conda/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/tornado/ioloop.py", line 780, in _discard_future_result
    future.result()
  File "/opt/conda/lib/python3.6/site-packages/dask_kubernetes/core.py", line 496, in _scale_up
    pods = await self._pods()
  File "/opt/conda/lib/python3.6/site-packages/dask_kubernetes/core.py", line 354, in _pods
    label_selector=format_labels(self.pod_template.metadata.labels)
  File "/opt/conda/lib/python3.6/site-packages/kubernetes_asyncio/client/api_client.py", line 165, in __call_api
    _request_timeout=_request_timeout)
  File "/opt/conda/lib/python3.6/site-packages/kubernetes_asyncio/client/rest.py", line 195, in GET
    query_params=query_params))
  File "/opt/conda/lib/python3.6/site-packages/kubernetes_asyncio/client/rest.py", line 175, in request
    r = await self.pool_manager.request(**args)
  File "/opt/conda/lib/python3.6/site-packages/aiohttp/client.py", line 417, in _request
    with timer:
  File "/opt/conda/lib/python3.6/site-packages/aiohttp/helpers.py", line 568, in __enter__
    raise RuntimeError('Timeout context manager should be used '
RuntimeError: Timeout context manager should be used inside a task
```

**Comment by jacobtomlinson** [comment]
Ah! No!

**Comment by mrocklin** [comment]
OK, things seem ok-ish on my machine at the moment using the CI environment.  Note that I had to update to Tornado 6 (not yet released, see https://github.com/tornadoweb/tornado/issues/2584).

The test `test_scale_up_down_fast` is failing, but I think that it may have been previously broken.  We'll need to overhaul our scaling code regardless.

If thing work here then I might merge this, then use black, then dive into scaling issues in another PR.

**Comment by mrocklin** [comment]
OK, we'll need to work on scaling.  I'm going to squash this down into a single commit and put this on a `dev` branch that I hope to be able to merge into master some day.  I'll raise a few issues for the work that I think needs to be done.

**Comment by mrocklin** [comment]
OK, merging.  I'll keep this branch alive in case people want to look through commit history in the near future (though I don't recommend it).

**Pull request merged**
