### PR TITLE
Fix logs with local scheduler

### LINKED ISSUE #231: Failed to fetch logs due to AttributeError
When playing with this [binder example](https://hub.aws-uswest2-binder.pangeo.io/user/rsignell-usgs-h-ke-water-levels-zwn763xk/notebooks/zarr_vs_zarr-hdf5.ipynb) we get an error when running:
> cluster.logs()

Notebook is using kube-cluster version 0.10 and distributed 2.9.0

error:

<details>

```python-traceback
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-12-1b877c3f8b87> in <module>
----> 1 cluster.logs()

/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/deploy/cluster.py in logs(self, scheduler, workers)
    193             each worker
    194         """
--> 195         return self.sync(self._logs, scheduler=scheduler, workers=workers)
    196 
    197     @property

/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/deploy/cluster.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    160             return future
    161         else:
--> 162             return sync(self.loop, func, *args, **kwargs)
    163 
    164     async def _logs(self, scheduler=True, workers=True):

/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    332     if error[0]:
    333         typ, exc, tb = error[0]
--> 334         raise exc.with_traceback(tb)
    335     else:
    336         return result[0]

/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/utils.py in f()
    316             if callback_timeout is not None:
    317                 future = gen.with_timeout(timedelta(seconds=callback_timeout), future)
--> 318             result[0] = yield future
    319         except Exception as exc:
    320             error[0] = sys.exc_info()

/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

/srv/conda/envs/notebook/lib/python3.7/site-packages/dask_kubernetes/core.py in _logs(self, scheduler, workers)
    603 
    604         if scheduler:
--> 605             logs["Scheduler"] = await self.scheduler.logs()
    606 
    607         if workers:

AttributeError: 'Scheduler' object has no attribute 'logs'
```

</details>

### PR DESCRIPTION
**Pull request by jacobtomlinson**
Should fix #231.

Switched the scheduler logs method to `get_logs` and added a shim to the `Scheduler` object to ensure compatibility.

Added tests for both remote and local schedulers.

### CODE REVIEW

**Comment by mrocklin** [comment]
+1 from me.  Alternatively, should we rename `get_logs` to `logs` upstream?  I'm ambivalent on the change, just thought I'd bring it up.

**Comment by jacobtomlinson** [comment]
I have a slight preference for `logs` but I do not have strong feelings.

**Comment by mrocklin** [comment]
Then I say go for it.  Part of my motivation here is also to make sure that you feel comfortable changing things upstream, and not just in dask-kubernetes.

**Comment by quasiben** [comment]
With https://github.com/dask/distributed/pull/3473 is this PR still needed ?

**Comment by jacobtomlinson** [comment]
Potentially `logs` should be renamed to `get_logs` and `logs` should be reinstated as the shim for backward compatibility.

**Pull request closed without merging**
