### PR TITLE
Enable overwrites of default environment variables

### PR DESCRIPTION
**Pull request by jonded94**
Should solve https://github.com/dask/dask-kubernetes/issues/873

### CODE REVIEW

**Review by jacobtomlinson — COMMENTED** [review]
This is great many thanks! Would you mind adding a small test to verify this behaviour?

**Comment by jonded94** [comment]
Was sure you'd ask that :smile:  I'm a bit unsure about that though. 

Changing the Scheduler address from the default address will likely lead to that Cluster being broken in the CI test? 
We could test though for a custom non-default Dask Worker name I guess? What do you think?

**Comment by jacobtomlinson** [comment]
> We could test though for a custom non-default Dask Worker name I guess?

Yep that sounds like a great way to test it.

**Comment by jonded94** [comment]
@jacobtomlinson sorry for the delay, was busy with other things. PR should now be ready; I included some tests that will use the apparently previously unused "simpleworkergroup.yaml" for deploying an additional worker group that overrides the envvar "DASK_WORKER_GROUP".
In the tests, it will check if the DASK_SCHEDULER still is intact.

**Review by jacobtomlinson — APPROVED** [review]
This looks great thanks!

**Comment by jonded94** [comment]
Ah, sure, sorry, will do that too tomorrow. This one doesn't need a test though (overriding the scheduler address is anyways a bit weird to test).

**Pull request merged**
